name: condaenv
dependencies:
  - torch=1.10.0
  - numpy=1.21.5
  - pandas=1.2.5
  - torchmetrics=0.7.1
  - pytorch-lightning=1.5.9
  - loguru=0.6.0
  - tqdm=4.62.3
  - typer=0.4.0
  - rasterio=1.2.10
  - albumentations=1.1.0
  - wandb=0.12.10
  - pip:
    - segmentation-models-pytorch==0.2.1
    - matplotlib==3.2.2
    - opencv-python==4.5.5.62
    - Pillow==7.1.2
    - xarray-spatial==0.3.2